// <copyright file="InvestmentDataTest.StockGroupGet.g.cs" company="Hewlett-Packard">Copyright © Hewlett-Packard 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Explorable;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Server.UserData
{
    public partial class InvestmentDataTest
    {
[TestMethod]
[PexGeneratedBy(typeof(InvestmentDataTest))]
public void StockGroupGet821()
{
    InvestmentData investmentData;
    string s;
    investmentData = PexInvariant.CreateInstance<InvestmentData>();
    PexInvariant.SetField<uint>((object)investmentData, "investmentPercentage", 0u);
    PexInvariant.SetField<string>
        ((object)investmentData, "stockGroup", (string)null);
    PexInvariant.CheckInvariant((object)investmentData);
    s = this.StockGroupGet(investmentData);
    Assert.AreEqual<string>((string)null, s);
    Assert.IsNotNull((object)investmentData);
    Assert.AreEqual<uint>(0u, investmentData.InvestmentPercentage);
    Assert.AreEqual<string>((string)null, investmentData.StockGroup);
}
    }
}
