// <copyright file="UserTest.SaveData.g.cs" company="Hewlett-Packard">Copyright © Hewlett-Packard 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.Pex.Framework.Explorable;
using Server;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Server.UserData
{
    public partial class UserTest
    {
[TestMethod]
[PexGeneratedBy(typeof(UserTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void SaveDataThrowsContractException315()
{
    try
    {
      List<InvestmentData> list;
      User user;
      List<InvestmentData> list1;
      InvestmentData[] investmentDatas = new InvestmentData[0];
      list = new List<InvestmentData>((IEnumerable<InvestmentData>)investmentDatas);
      byte[] bs = new byte[0];
      byte[] bs1 = new byte[0];
      user = PexInvariant.CreateInstance<User>();
      PexInvariant.SetField<DateTime>((object)user, "expires", default(DateTime));
      PexInvariant.SetField<decimal>((object)user, "funds", default(decimal));
      PexInvariant.SetField<int>((object)user, "id", 0);
      PexInvariant.SetField<List<InvestmentData>>((object)user, "investments", list);
      PexInvariant.SetField<byte[]>((object)user, "iv", bs);
      PexInvariant.SetField<byte[]>((object)user, "keyFile", bs1);
      PexInvariant.SetField<ServerClass>((object)user, "server", (ServerClass)null);
      PexInvariant.SetField<string>((object)user, "username", "\u0100");
      PexInvariant.CheckInvariant((object)user);
      InvestmentData[] investmentDatas1 = new InvestmentData[1];
      list1 =
        new List<InvestmentData>((IEnumerable<InvestmentData>)investmentDatas1);
      this.SaveData(user, list1);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(UserTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void SaveDataThrowsContractException64()
{
    try
    {
      List<InvestmentData> list;
      User user;
      InvestmentData[] investmentDatas = new InvestmentData[0];
      list = new List<InvestmentData>((IEnumerable<InvestmentData>)investmentDatas);
      byte[] bs = new byte[0];
      byte[] bs1 = new byte[0];
      user = PexInvariant.CreateInstance<User>();
      PexInvariant.SetField<DateTime>((object)user, "expires", default(DateTime));
      PexInvariant.SetField<decimal>((object)user, "funds", default(decimal));
      PexInvariant.SetField<int>((object)user, "id", 0);
      PexInvariant.SetField<List<InvestmentData>>((object)user, "investments", list);
      PexInvariant.SetField<byte[]>((object)user, "iv", bs);
      PexInvariant.SetField<byte[]>((object)user, "keyFile", bs1);
      PexInvariant.SetField<ServerClass>((object)user, "server", (ServerClass)null);
      PexInvariant.SetField<string>((object)user, "username", "\u0100");
      PexInvariant.CheckInvariant((object)user);
      this.SaveData(user, list);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(UserTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void SaveDataThrowsContractException936()
{
    try
    {
      List<InvestmentData> list;
      User user;
      InvestmentData[] investmentDatas = new InvestmentData[0];
      list = new List<InvestmentData>((IEnumerable<InvestmentData>)investmentDatas);
      byte[] bs = new byte[0];
      byte[] bs1 = new byte[0];
      user = PexInvariant.CreateInstance<User>();
      PexInvariant.SetField<DateTime>((object)user, "expires", default(DateTime));
      PexInvariant.SetField<decimal>((object)user, "funds", default(decimal));
      PexInvariant.SetField<int>((object)user, "id", 0);
      PexInvariant.SetField<List<InvestmentData>>((object)user, "investments", list);
      PexInvariant.SetField<byte[]>((object)user, "iv", bs);
      PexInvariant.SetField<byte[]>((object)user, "keyFile", bs1);
      PexInvariant.SetField<ServerClass>((object)user, "server", (ServerClass)null);
      PexInvariant.SetField<string>((object)user, "username", "\u0100");
      PexInvariant.CheckInvariant((object)user);
      this.SaveData(user, (List<InvestmentData>)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
